primer_list: data/14-1001-cut-and-run-library-prep-kit-primers.csv
samples:
  sample_1:
    ref: data/asm/asm.fa
    data:
      treatment:
        primer:
        - ["", ""]
        path: data/CENP-A/reads.bam
      control:
        primer:
        - ["", ""]
        path: data/IgG/reads.bam
    min_length: 100
    max_length: 100000
    min_mapq: 0
    binsize: 5000
